version: "3.7"
networks:
  # the internal network is a bridge network used by the api container and database
  # We could also bypass this in favor of port fowarding to the host machine and
  # communicating over tcp through the host, but this showcases a way to use docker's internal DNS to
  # resolve networks
  internal:
    name: spotify_app_internal
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.17.0.0/16
services:

  db:
    container_name: PrimaryDB
    image:
    networks:
      - internal
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
