# Generated by Django 4.0.5 on 2022-06-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(max_length=6)),
                ('track_id', models.CharField(max_length=128)),
                ('playlist_id', models.CharField(max_length=128)),
                ('occurrence', models.IntegerField(default=1)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
    ]
